version: '3'
services: 
    web: 
        build: 
            dockerfile: Dockerfile
            context: .
        container_name: site
        restart: unless-stopped
        environment:
            API_URL: http://localhost:6081/api
            API_BANCO: database
        ports:
            - "6080:80"
        volumes:
            - ./conf/nginx/nginx.conf:/etc/nginx/
            - ./site/arquivos:/arquivos/
    #MySQL Service
    db:
        image: mysql:5.7.22
        container_name: db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
           MYSQL_DATABASE: database
           MYSQL_ROOT_PASSWORD: senha
           SERVICE_TAGS: dev
           SERVICE_NAME: mysql
        volumes:
          - ./conf/mysql/my.cnf:/etc/mysql/
          - ./database:/var/lib/mysql
#Volumes
volumes:
    database:
        driver: local